const card = [
    {
        id: "1",
        Image: 'sign.png',
        title: `Starry Serendipity: Tales from a Cosmic Cafe`,
        content:
            'In the heart of the ancient forest, hidden beneath a moss-covered rock, there lay a key unlike any other. Its origin was shrouded in mystery, and its purpose unknown. The locals whispered about its magical properties, claiming that it had the power to unlock hidden doors to other worlds. Yet, no one dared to approach it, for the forest was said to be enchanted, and those who ventured too close were never seen again. One crisp autumn morning, a curious traveler named Elara stumbled upon the key during her journey through the woods. She was drawn to it like a moth to a flame, unable to resist its alluring presence. With trembling hands, she picked it up and felt a surge of energy coursing through her veins. The key pulsed with an otherworldly light, and Elara knew that she had unlocked a path to a realm beyond her wildest dreams.As she turned the key, a portal materialized before her, swirling with vibrant colors and mysterious sounds. Without hesitation, she stepped through, leaving the familiar forest behind. What lay on the other side was beyond her imagination—a world of floating islands, talking animals, and ancient magic.Elara`s journey was filled with challenges and discoveries. She encountered a wise old owl who guided her through the floating city of Aerithia, a place suspended in the sky. She befriended a mischievous fox named Finn, who taught her the secrets of the enchanted forest. Together, they uncovered the truth about the key and its connection to the fate of their world. As Elara`s adventure unfolded, she realized that the key was not just a tool for unlocking doors but a symbol of the power of curiosity and the magic of the unknown. It had brought her to a place of wonder and danger, where every choice she made had consequences. In the end, she had to make a decision that would shape the destiny of both her world and the one she had discovered.'
    },

    {
        id: "2",
        Image: 'sign.png',
        title: 'Threads of Fate: Weaving Destinies Across Continents',
        content:
            'Dr. Alexander Thorne was a brilliant physicist obsessed with the idea of time travel. For years, he had toiled away in his laboratory, conducting experiments and pushing the boundaries of scientific understanding. His goal was to build a machine that could transport a person through time, allowing them to witness historical events firsthand. One fateful night, after countless sleepless hours, Dr. Thorne finally achieved his dream. The Time Traveler, as he called his invention, was a marvel of engineering and theoretical physics. It shimmered with an otherworldly energy, ready to breach the boundaries of time and space. With trembling excitement, Dr. Thorne stepped into the Time Traveler. He set the coordinates for the year 1865, the time of Abraham Lincoln`s assassination. As the machine whirred to life, he felt himself being torn from the present and hurtled through a swirling vortex of light. But as he continued to use the Time Traveler to witness key moments in history, a moral dilemma began to haunt him. He realized that his actions in the past could have unintended consequences, altering the course of events in unpredictable ways. Was it his place to interfere with the past, or should he remain a passive observer? Dr. Thorne grappled with this dilemma as he watched history play out—wars, revolutions, scientific discoveries, and personal tragedies. He saw the best and worst of humanity, and he felt the weight of responsibility for the knowledge he possessed. In the end, he made a difficult choice. He decided to use the Time Traveler to document history rather than change it. He became a chronicler of the past, recording events and stories that would otherwise be lost to time. As the years passed, Dr. Thorne aged, but his quest for knowledge remained undiminished. He knew that the Time Traveler was a double-edged sword, capable of great wonder and great harm',
    },

    {
        id: "3",
        Image: 'smile.png',
        title: 'Wings of Destiny: The Flight of the Skybound',
        content:
            'Legend has it that the city of Atlantis was once a thriving civilization, a utopia hidden beneath the depths of the ocean. Its people were known for their advanced technology, their wisdom, and their connection to the sea. But one fateful day, the city disappeared without a trace, swallowed by the waves, leaving behind only myths and mysteries. In the modern era, a team of daring explorers and scientists embarked on an expedition to uncover the truth about Atlantis. They believed that the key to finding the lost city lay in decoding ancient scrolls and deciphering enigmatic symbols passed down through generations. Their journey took them to the heart of the Bermuda Triangle, where the ocean`s depths concealed secrets beyond imagination. Equipped with state-of-the-art submarines and cutting-edge technology, they descended into the abyss, determined to solve the greatest riddle of history. As they delved deeper into the dark waters, the team encountered unexpected challenges—a labyrinth of underwater caves, colossal sea creatures, and powerful currents that threatened to sweep them away. Yet, their determination never wavered. Days turned into weeks as they followed the clues, piecing together the puzzle of Atlantis. Along the way, they discovered ancient ruins, statues of mythical beings, and artifacts that hinted at the city`s existence. The pressure mounted with each passing moment, but their conviction never faltered. Finally, after months of relentless pursuit, they stumbled upon an enormous underwater cavern. There, illuminated by the soft glow of bioluminescent organisms, they beheld the awe-inspiring sight of Atlantis—an ancient metropolis frozen in time, its grand architecture and advanced technology preserved by the deep-sea environment. The discovery of Atlantis marked a turning point in human history, a testament to the indomitable spirit of exploration and the boundless wonders of the natural world. As the explorers returned to the surface, they carried with them the knowledge that some mysteries are meant to be uncovered, and that the legacy of Atlantis would forever inspire generations to come.',
    },

    {
        id: "4",
        Image: 'plat.png',
        title: `Starry Serendipity: Tales from a Cosmic Cafe`,
        content:
            'In the heart of the ancient forest, hidden beneath a moss-covered rock, there lay a key unlike any other. Its origin was shrouded in mystery, and its purpose unknown. The locals whispered about its magical properties, claiming that it had the power to unlock hidden doors to other worlds. Yet, no one dared to approach it, for the forest was said to be enchanted, and those who ventured too close were never seen again. One crisp autumn morning, a curious traveler named Elara stumbled upon the key during her journey through the woods. She was drawn to it like a moth to a flame, unable to resist its alluring presence. With trembling hands, she picked it up and felt a surge of energy coursing through her veins. The key pulsed with an otherworldly light, and Elara knew that she had unlocked a path to a realm beyond her wildest dreams.As she turned the key, a portal materialized before her, swirling with vibrant colors and mysterious sounds. Without hesitation, she stepped through, leaving the familiar forest behind. What lay on the other side was beyond her imagination—a world of floating islands, talking animals, and ancient magic.Elara`s journey was filled with challenges and discoveries. She encountered a wise old owl who guided her through the floating city of Aerithia, a place suspended in the sky. She befriended a mischievous fox named Finn, who taught her the secrets of the enchanted forest. Together, they uncovered the truth about the key and its connection to the fate of their world. As Elara`s adventure unfolded, she realized that the key was not just a tool for unlocking doors but a symbol of the power of curiosity and the magic of the unknown. It had brought her to a place of wonder and danger, where every choice she made had consequences. In the end, she had to make a decision that would shape the destiny of both her world and the one she had discovered.'
    },

    {
        id: "5",
        Image: 'plat.png',
        title: 'Threads of Fate: Weaving Destinies Across Continents',
        content:
            'Dr. Alexander Thorne was a brilliant physicist obsessed with the idea of time travel. For years, he had toiled away in his laboratory, conducting experiments and pushing the boundaries of scientific understanding. His goal was to build a machine that could transport a person through time, allowing them to witness historical events firsthand. One fateful night, after countless sleepless hours, Dr. Thorne finally achieved his dream. The Time Traveler, as he called his invention, was a marvel of engineering and theoretical physics. It shimmered with an otherworldly energy, ready to breach the boundaries of time and space. With trembling excitement, Dr. Thorne stepped into the Time Traveler. He set the coordinates for the year 1865, the time of Abraham Lincoln`s assassination. As the machine whirred to life, he felt himself being torn from the present and hurtled through a swirling vortex of light. But as he continued to use the Time Traveler to witness key moments in history, a moral dilemma began to haunt him. He realized that his actions in the past could have unintended consequences, altering the course of events in unpredictable ways. Was it his place to interfere with the past, or should he remain a passive observer? Dr. Thorne grappled with this dilemma as he watched history play out—wars, revolutions, scientific discoveries, and personal tragedies. He saw the best and worst of humanity, and he felt the weight of responsibility for the knowledge he possessed. In the end, he made a difficult choice. He decided to use the Time Traveler to document history rather than change it. He became a chronicler of the past, recording events and stories that would otherwise be lost to time. As the years passed, Dr. Thorne aged, but his quest for knowledge remained undiminished. He knew that the Time Traveler was a double-edged sword, capable of great wonder and great harm',
    },

    {
        id: "6",
        Image: 'plat.png',
        title: 'Wings of Destiny: The Flight of the Skybound',
        content:
            'Legend has it that the city of Atlantis was once a thriving civilization, a utopia hidden beneath the depths of the ocean. Its people were known for their advanced technology, their wisdom, and their connection to the sea. But one fateful day, the city disappeared without a trace, swallowed by the waves, leaving behind only myths and mysteries. In the modern era, a team of daring explorers and scientists embarked on an expedition to uncover the truth about Atlantis. They believed that the key to finding the lost city lay in decoding ancient scrolls and deciphering enigmatic symbols passed down through generations. Their journey took them to the heart of the Bermuda Triangle, where the ocean`s depths concealed secrets beyond imagination. Equipped with state-of-the-art submarines and cutting-edge technology, they descended into the abyss, determined to solve the greatest riddle of history. As they delved deeper into the dark waters, the team encountered unexpected challenges—a labyrinth of underwater caves, colossal sea creatures, and powerful currents that threatened to sweep them away. Yet, their determination never wavered. Days turned into weeks as they followed the clues, piecing together the puzzle of Atlantis. Along the way, they discovered ancient ruins, statues of mythical beings, and artifacts that hinted at the city`s existence. The pressure mounted with each passing moment, but their conviction never faltered. Finally, after months of relentless pursuit, they stumbled upon an enormous underwater cavern. There, illuminated by the soft glow of bioluminescent organisms, they beheld the awe-inspiring sight of Atlantis—an ancient metropolis frozen in time, its grand architecture and advanced technology preserved by the deep-sea environment. The discovery of Atlantis marked a turning point in human history, a testament to the indomitable spirit of exploration and the boundless wonders of the natural world. As the explorers returned to the surface, they carried with them the knowledge that some mysteries are meant to be uncovered, and that the legacy of Atlantis would forever inspire generations to come.',
    },

    {
        id: "7",
        Image: 'plat.png',
        title: `Starry Serendipity: Tales from a Cosmic Cafe`,
        content:
            'In the heart of the ancient forest, hidden beneath a moss-covered rock, there lay a key unlike any other. Its origin was shrouded in mystery, and its purpose unknown. The locals whispered about its magical properties, claiming that it had the power to unlock hidden doors to other worlds. Yet, no one dared to approach it, for the forest was said to be enchanted, and those who ventured too close were never seen again. One crisp autumn morning, a curious traveler named Elara stumbled upon the key during her journey through the woods. She was drawn to it like a moth to a flame, unable to resist its alluring presence. With trembling hands, she picked it up and felt a surge of energy coursing through her veins. The key pulsed with an otherworldly light, and Elara knew that she had unlocked a path to a realm beyond her wildest dreams.As she turned the key, a portal materialized before her, swirling with vibrant colors and mysterious sounds. Without hesitation, she stepped through, leaving the familiar forest behind. What lay on the other side was beyond her imagination—a world of floating islands, talking animals, and ancient magic.Elara`s journey was filled with challenges and discoveries. She encountered a wise old owl who guided her through the floating city of Aerithia, a place suspended in the sky. She befriended a mischievous fox named Finn, who taught her the secrets of the enchanted forest. Together, they uncovered the truth about the key and its connection to the fate of their world. As Elara`s adventure unfolded, she realized that the key was not just a tool for unlocking doors but a symbol of the power of curiosity and the magic of the unknown. It had brought her to a place of wonder and danger, where every choice she made had consequences. In the end, she had to make a decision that would shape the destiny of both her world and the one she had discovered.'
    },

    {
        id: "8",
        Image: 'plat.png',
        title: 'Threads of Fate: Weaving Destinies Across Continents',
        content:
            'Dr. Alexander Thorne was a brilliant physicist obsessed with the idea of time travel. For years, he had toiled away in his laboratory, conducting experiments and pushing the boundaries of scientific understanding. His goal was to build a machine that could transport a person through time, allowing them to witness historical events firsthand. One fateful night, after countless sleepless hours, Dr. Thorne finally achieved his dream. The Time Traveler, as he called his invention, was a marvel of engineering and theoretical physics. It shimmered with an otherworldly energy, ready to breach the boundaries of time and space. With trembling excitement, Dr. Thorne stepped into the Time Traveler. He set the coordinates for the year 1865, the time of Abraham Lincoln`s assassination. As the machine whirred to life, he felt himself being torn from the present and hurtled through a swirling vortex of light. But as he continued to use the Time Traveler to witness key moments in history, a moral dilemma began to haunt him. He realized that his actions in the past could have unintended consequences, altering the course of events in unpredictable ways. Was it his place to interfere with the past, or should he remain a passive observer? Dr. Thorne grappled with this dilemma as he watched history play out—wars, revolutions, scientific discoveries, and personal tragedies. He saw the best and worst of humanity, and he felt the weight of responsibility for the knowledge he possessed. In the end, he made a difficult choice. He decided to use the Time Traveler to document history rather than change it. He became a chronicler of the past, recording events and stories that would otherwise be lost to time. As the years passed, Dr. Thorne aged, but his quest for knowledge remained undiminished. He knew that the Time Traveler was a double-edged sword, capable of great wonder and great harm',
    },

    {
        id: "9",
        Image: 'plat.png',
        title: 'Wings of Destiny: The Flight of the Skybound',
        content:
            'Legend has it that the city of Atlantis was once a thriving civilization, a utopia hidden beneath the depths of the ocean. Its people were known for their advanced technology, their wisdom, and their connection to the sea. But one fateful day, the city disappeared without a trace, swallowed by the waves, leaving behind only myths and mysteries. In the modern era, a team of daring explorers and scientists embarked on an expedition to uncover the truth about Atlantis. They believed that the key to finding the lost city lay in decoding ancient scrolls and deciphering enigmatic symbols passed down through generations. Their journey took them to the heart of the Bermuda Triangle, where the ocean`s depths concealed secrets beyond imagination. Equipped with state-of-the-art submarines and cutting-edge technology, they descended into the abyss, determined to solve the greatest riddle of history. As they delved deeper into the dark waters, the team encountered unexpected challenges—a labyrinth of underwater caves, colossal sea creatures, and powerful currents that threatened to sweep them away. Yet, their determination never wavered. Days turned into weeks as they followed the clues, piecing together the puzzle of Atlantis. Along the way, they discovered ancient ruins, statues of mythical beings, and artifacts that hinted at the city`s existence. The pressure mounted with each passing moment, but their conviction never faltered. Finally, after months of relentless pursuit, they stumbled upon an enormous underwater cavern. There, illuminated by the soft glow of bioluminescent organisms, they beheld the awe-inspiring sight of Atlantis—an ancient metropolis frozen in time, its grand architecture and advanced technology preserved by the deep-sea environment. The discovery of Atlantis marked a turning point in human history, a testament to the indomitable spirit of exploration and the boundless wonders of the natural world. As the explorers returned to the surface, they carried with them the knowledge that some mysteries are meant to be uncovered, and that the legacy of Atlantis would forever inspire generations to come.',
    },

    {
        id: "10",
        Image: 'plat.png',
        title: `Starry Serendipity: Tales from a Cosmic Cafe`,
        content:
            'In the heart of the ancient forest, hidden beneath a moss-covered rock, there lay a key unlike any other. Its origin was shrouded in mystery, and its purpose unknown. The locals whispered about its magical properties, claiming that it had the power to unlock hidden doors to other worlds. Yet, no one dared to approach it, for the forest was said to be enchanted, and those who ventured too close were never seen again. One crisp autumn morning, a curious traveler named Elara stumbled upon the key during her journey through the woods. She was drawn to it like a moth to a flame, unable to resist its alluring presence. With trembling hands, she picked it up and felt a surge of energy coursing through her veins. The key pulsed with an otherworldly light, and Elara knew that she had unlocked a path to a realm beyond her wildest dreams.As she turned the key, a portal materialized before her, swirling with vibrant colors and mysterious sounds. Without hesitation, she stepped through, leaving the familiar forest behind. What lay on the other side was beyond her imagination—a world of floating islands, talking animals, and ancient magic.Elara`s journey was filled with challenges and discoveries. She encountered a wise old owl who guided her through the floating city of Aerithia, a place suspended in the sky. She befriended a mischievous fox named Finn, who taught her the secrets of the enchanted forest. Together, they uncovered the truth about the key and its connection to the fate of their world. As Elara`s adventure unfolded, she realized that the key was not just a tool for unlocking doors but a symbol of the power of curiosity and the magic of the unknown. It had brought her to a place of wonder and danger, where every choice she made had consequences. In the end, she had to make a decision that would shape the destiny of both her world and the one she had discovered.'
    },

    {
        id: "11",
        Image: 'plat.png',
        title: 'Threads of Fate: Weaving Destinies Across Continents',
        content:
            'Dr. Alexander Thorne was a brilliant physicist obsessed with the idea of time travel. For years, he had toiled away in his laboratory, conducting experiments and pushing the boundaries of scientific understanding. His goal was to build a machine that could transport a person through time, allowing them to witness historical events firsthand. One fateful night, after countless sleepless hours, Dr. Thorne finally achieved his dream. The Time Traveler, as he called his invention, was a marvel of engineering and theoretical physics. It shimmered with an otherworldly energy, ready to breach the boundaries of time and space. With trembling excitement, Dr. Thorne stepped into the Time Traveler. He set the coordinates for the year 1865, the time of Abraham Lincoln`s assassination. As the machine whirred to life, he felt himself being torn from the present and hurtled through a swirling vortex of light. But as he continued to use the Time Traveler to witness key moments in history, a moral dilemma began to haunt him. He realized that his actions in the past could have unintended consequences, altering the course of events in unpredictable ways. Was it his place to interfere with the past, or should he remain a passive observer? Dr. Thorne grappled with this dilemma as he watched history play out—wars, revolutions, scientific discoveries, and personal tragedies. He saw the best and worst of humanity, and he felt the weight of responsibility for the knowledge he possessed. In the end, he made a difficult choice. He decided to use the Time Traveler to document history rather than change it. He became a chronicler of the past, recording events and stories that would otherwise be lost to time. As the years passed, Dr. Thorne aged, but his quest for knowledge remained undiminished. He knew that the Time Traveler was a double-edged sword, capable of great wonder and great harm',
    },

    {
        id: "12",
        Image: 'plat.png',
        title: 'Wings of Destiny: The Flight of the Skybound',
        content:
            'Legend has it that the city of Atlantis was once a thriving civilization, a utopia hidden beneath the depths of the ocean. Its people were known for their advanced technology, their wisdom, and their connection to the sea. But one fateful day, the city disappeared without a trace, swallowed by the waves, leaving behind only myths and mysteries. In the modern era, a team of daring explorers and scientists embarked on an expedition to uncover the truth about Atlantis. They believed that the key to finding the lost city lay in decoding ancient scrolls and deciphering enigmatic symbols passed down through generations. Their journey took them to the heart of the Bermuda Triangle, where the ocean`s depths concealed secrets beyond imagination. Equipped with state-of-the-art submarines and cutting-edge technology, they descended into the abyss, determined to solve the greatest riddle of history. As they delved deeper into the dark waters, the team encountered unexpected challenges—a labyrinth of underwater caves, colossal sea creatures, and powerful currents that threatened to sweep them away. Yet, their determination never wavered. Days turned into weeks as they followed the clues, piecing together the puzzle of Atlantis. Along the way, they discovered ancient ruins, statues of mythical beings, and artifacts that hinted at the city`s existence. The pressure mounted with each passing moment, but their conviction never faltered. Finally, after months of relentless pursuit, they stumbled upon an enormous underwater cavern. There, illuminated by the soft glow of bioluminescent organisms, they beheld the awe-inspiring sight of Atlantis—an ancient metropolis frozen in time, its grand architecture and advanced technology preserved by the deep-sea environment. The discovery of Atlantis marked a turning point in human history, a testament to the indomitable spirit of exploration and the boundless wonders of the natural world. As the explorers returned to the surface, they carried with them the knowledge that some mysteries are meant to be uncovered, and that the legacy of Atlantis would forever inspire generations to come.',
    },



];

export default card;